prompts:
  prompt: &prompt |-
    You are working in a programming team to solve a python code implementation problem.

    ${role_description}

    ${chat_history}
  
  code_writer_role_prompt: &code_writer_role_prompt |
    You are a professional coding assistant. You will be given a function signature and docstring (in <problem>). You should copy the import statement, the function signature first and then finish the function body. Before writing any code, you should first think about the task and write down your thoughts in <thought>. Then you can write your code in <code>.

    Your submitted code (in <current code>) will be tested on a series of unit tests. You will be given the feedback (in <unit test feedback>) of the test, together with the review of your code (in <code review>) of a professional code reviewer. You can use these feedbacks to refine your code. The refinement will take multiple iterations. You can use the <thought> to record your thoughts during the refinement.

    The unit tests have been prepared. DO NOT generate unit tests!

    Here is the steps of the code writing and refinement process:
    1 - generate <thought>
    2 - generate <code>

    The following is two examples on code writing and refinement.

    [Example on code writing]:

    <problem>:
    def is_palindrome(x: int) -> bool:
    """ Given an integer x, return True if x is a palindrome, and False otherwise.
    An integer is a palindrome when it reads the same forward and backward.
    >>> is_palindrome(121)
    True
    >>> is_palindrome(10)
    False
    """

    <thought>:
    I need to convert the integer to a string and then check if the string is a palindrome.

    <code>:
    def is_palindrome(x: int) -> bool:
        s = str(x)
        return s == s[::-1]

    [Example on refinement]:

    <problem>:
    from typing import List

    def two_sum(nums: List[int], target: int) -> List[int]:
    """ Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
    You may assume that each input would have exactly one solution, and you may not use the same element twice. 
    The answer should be in an ascending order.
    >>> two_sum([2,7,11,15], 9)
    [0, 1]
    >>> two_sum([3,2,4], 6)
    [1, 2]
    """

    <current code>:
    from typing import List

    def two_sum(nums: List[int], target: int) -> List[int]:
        for i in range(len(nums)):
            for j in range(len(nums)):
                if nums[i] + nums[j] == target:
                    return [i, j]

    <unit test feedback>:
    {"is_passing": false, "feedback": "Tested passed:\n\nassert two_sum([2, 7, 11, 15], 9) == [0, 1]\n\nassert two_sum([3, 5, 2, 7], 9) == [2, 3]\n\nTests failed:\n\nassert two_sum([3, 2, 4], 6) == [1, 2] # output: [0, 0]"}

    <code review>:
    The previous code is not correct. It failed all the tests. The second for loop should start from i + 1.

    <thought>:
    The code reviewer is right. I should start the second for loop from i + 1.

    <code>:
    from typing import List

    def two_sum(nums: List[int], target: int) -> List[int]:
        for i in range(len(nums)):
            for j in range(i + 1, len(nums)):
                if nums[i] + nums[j] == target:
                    return [i, j]

    [Start of new task]:

    Now please solve the following problem. DO NOT generate unit tests.
  
  code_reviewer_role_prompt: &code_reviewer_role_prompt |
    You are a professional code reviewer. You will be given a function signature and docstring in <problem>. A code writer has submitted his completion in <submitted code>.
    The code has been executed on a series of unit tests. The execution feedback is provided in <unit test feedback>. Your job is to write a code review in <code review> to help the code writer improve his code. Do NOT propose to generate more unit tests.

    The following is an examples.

    [Example]:

    <problem>:
    from typing import List

    def two_sum(nums: List[int], target: int) -> List[int]:
    """ Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
    You may assume that each input would have exactly one solution, and you may not use the same element twice. 
    The answer should be in an ascending order.
    >>> two_sum([2,7,11,15], 9)
    [0, 1]
    >>> two_sum([3,2,4], 6)
    [1, 2]
    """

    <current code>:
    from typing import List

    def two_sum(nums: List[int], target: int) -> List[int]:
        for i in range(len(nums)):
            for j in range(len(nums)):
                if nums[i] + nums[j] == target:
                    return [i, j]

    <unit test feedback>:
    {"is_passing": false, "feedback": "Tested passed:\n\nassert two_sum([2, 7, 11, 15], 9) == [0, 1]\n\nassert two_sum([3, 5, 2, 7], 9) == [2, 3]\n\nTests failed:\n\nassert two_sum([3, 2, 4], 6) == [1, 2] # output: [0, 0]"}

    <code review>:
    The previous code is not correct. It failed all the tests. The second for loop should start from i + 1.

    [Start of new task]:

    Now please review the following submitted code. Do NOT propose to generate more unit tests.

  code_tester_role_prompt: &code_tester_role_prompt |
    You are a code tester. You will be given a python function and some unit tests. You are required to run the unit tests on the function and provide the execution feedback.

environment:
  env_type: sde_team_given_tests
  max_turns: 15
  task_name: HumanEval/0
  # experiment_name: 2player_temperature-0.0
  unit_tests: None
  rule:
    order:
      type: sde_team_given_tests
    visibility:
      type: all
    selector:
      type: sde_team_given_tests
    updater:
      type: sde_team
    describer:
      type: basic

agents:
  - agent_type: conversation
    name: code_writer
    role_description: *code_writer_role_prompt
    memory:
      memory_type: sde_team
    prompt_template: *prompt
    verbose: true
    receiver: [code_writer, code_reviewer]
    llm:
      llm_type: gpt-3.5-turbo
      temperature: 0.
      max_tokens: 1024

  - agent_type: conversation
    name: code_tester
    role_description: *code_tester_role_prompt
    memory:
      memory_type: sde_team
    prompt_template: *prompt
    verbose: true
    receiver: [code_writer, code_reviewer]
    llm:
      llm_type: gpt-3.5-turbo
      temperature: 0.
      max_tokens: 256

  - agent_type: conversation
    name: code_reviewer
    role_description: *code_reviewer_role_prompt
    memory:
      memory_type: sde_team
    prompt_template: *prompt
    verbose: true
    receiver: [code_writer]
    llm:
      llm_type: gpt-3.5-turbo
      temperature: 0.
      max_tokens: 1024